--- #YAML:1.0
name:                SMS-Send-DE-MeinBMW
version:             0.04
abstract:            An SMS::Send driver for the www.meinbmw.de website
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Carp:                          0
    HTML::Form:                    0
    HTTP::Cookies:                 0
    HTTP::Request::Common:         0
    HTTP::Response:                0
    LWP::UserAgent:                0
    SMS::Send:                     0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Boris Zentner <bzm@2bz.de>
