# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SMS-Send-DE-MeinBMW
version:      0.06
version_from: lib/SMS/Send/DE/MeinBMW.pm
installdirs:  site
requires:
    Carp:                          0
    HTML::Form:                    0
    HTTP::Cookies:                 0
    HTTP::Request::Common:         0
    HTTP::Response:                0
    LWP::UserAgent:                0
    SMS::Send::Driver:             0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
